### ISSUE TITLE
setTimeout should not be called from render

### ISSUE THREAD

**Issue by bvaughn** [kirill-konshin/react-virtualized-image-measurer#1]
I'm not sure why [this `setTimeout` call](https://github.com/kirill-konshin/react-virtualized-image-measurer/blob/28f8d852462ab2c0b66747150a6462680d31b916/src/index.js#L120) is necessary- but it looks like it will cause trouble for async rendering.

If the call is necessary, I would suggest moving it to `componentDidMount` / `componentDidUpdate`.

(See [this blog post](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) and [the `StrictMode` docs](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects) for more background information.)

**Comment by kirill-konshin** [comment]
This is needed in order to still call `onLoad` if image cannot be loaded within certain timeframe.

Thanks for your suggestion, moved it to `componentDidUpdate`.

Released `0.1.1`.
