### ISSUE TITLE
same image url, but separate image

### ISSUE THREAD

**Issue by vladp** [kirill-konshin/react-virtualized-image-measurer#2]
Hello, 
thank you for making the library, and working example with Masonry component available.
It was exactly what I needed.

There is a use case, however, that you might not have envisaged supporting.

In my case, a client can request an image from the server, that is not available. In this case, my server generates a 'default image', basically a fancy question mark.

If I have more than one question-mark images, the ImageMeasurer component causes a react error complain that multiple elements cannot have the same key.
this happens, because you are using image url, as a key.  And in this use case, it will be the same.

Is a way for me to change the key assignment?

thank you.

**Comment by kirill-konshin** [comment]
Nice catch! You can always filter duplicates before providing the array to the component. In the mean time I will think about more robust fix. PR is welcome.

**Comment by vladp** [comment]
thx, will think of a solution. I do want the duplicates to be shown, in my case (in other words, I want to let the user know that there is an item matching his/her criteria -- but the item just does not have an image).

**Comment by kirill-konshin** [comment]
My idea was slightly different. Component provides indexed measurements in sizes prop, you can feed in the filtered array but use original array to iterate and manually get measurements from this prop. Don’t forget to stop iteration if size was not found.

Another option is to save the path to such empty image, use it in destination component and make a map of original array with null instead of those images. Library will skip them.

**Comment by vladp** [comment]
Ah, ok. I think I understand.   Will try.

For every item in my list I have a unique key, so perhaps allow ImageMeasurer to take a property that takes a function and allows a user to specify a key, could also be used.

In general, it seems like allowing react components to have 'logical' keys (rather than auto generated), allows for better performance when items are reordered or deleted.
I tried to follow discussion WRT custom getter/setter  
https://github.com/bvaughn/react-virtualized/pull/789

---

While on the topic of user-configurable properties.  I noticed you are setting styles for span components.  

I am having some difficulties with my page, as it is not letting my react-bootstrap navbar collapse in front of the Masonry Grid (eg to remain  to  be visible, instead it seems to be hidden behind the images).
I am not yet sure where the problem is (debugging CSS of react-bootstrap and Masonry is quite a challenge).   
But wanted to check, if you could suggest where I should look for conflicting styles.

[**Update:**]  Fixed (at least partially), by setting React-Bootstrap navbar to be **fixedTop**.

Image with the initial problem:

![masonry_zindex__bootstrap3](https://user-images.githubusercontent.com/94890/40037630-437eb61e-57dc-11e8-88c4-d2b21aeb9f25.gif)

**Comment by kirill-konshin** [comment]
Thanks for the suggestion, `keyGetter` would be a nice solution. I will do it in the next few days.

**Comment by kirill-konshin** [comment]
Can't help with styles, sorry, it's very dependent on your project.

**Comment by kirill-konshin** [comment]
Released `0.2.0`

**Comment by vladp** [comment]
Thank you for making the updates.

There is a small issue, that perhaps you could fix.

When I define a function to access my key, it fails to run, with an explanation that key property is not a function.

Reason it is happening, because  'key' is not a property that you can access by 'this.props' method.
It is basically a reserved keyword for React.

See

https://stackoverflow.com/questions/27632901/react-wont-pass-a-particular-value-to-props?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

A simple change would be, that ImageMeasurer component allows 
keyGetter   property, rather than 'key' property.
(and of course, before calling a function, since this is an optional property,
 you want to check that it was  defined).

And then everything will work then.

Thank you again

**Comment by kirill-konshin** [comment]
Oops. Released `0.3.0`.

**Comment by vladp** [comment]
works great now. thank you
