### ISSUE TITLE
This breaks if you change the items array.

### ISSUE THREAD

**Issue by ofersadgat** [kirill-konshin/react-virtualized-image-measurer#3]
The callback will be called with all images that have ever passed through the measurer instead of only those which are in the items array.

**Comment by kirill-konshin** [comment]
Some background... Masonry is optimized to add items, not rearrange them or place something in the middle. The idea of this component is to display a growing array.

Can you please explain what do you mean "callback will be called with all images that have ever passed through the measurer" — all logic is based on `props.items`: https://github.com/kirill-konshin/react-virtualized-image-measurer/blob/master/src/index.js#L78.

**Comment by ofersadgat** [comment]
Yeah, the problem I'm having is that I'm using masonry to display images. However, when I try and filter the list, nothing is filtered because the image measurer doesnt filter the output. I.e. when prop.items is reduced in length, `this.state` never recalculates.

**Comment by kirill-konshin** [comment]
This is weird because change of items should lead to re-render and so to firing new onLoad events which in turn will cause new set of items to be passed down to Masonry. Can you create a small codesandbox snippet with so that I will be able to reproduce? You can clone the demo: https://codesandbox.io/s/7y66p25qv6.

**Comment by ofersadgat** [comment]
https://codesandbox.io/s/10nvrl03xq


See how the list doesnt get shorter (when you click on resize)?

**Comment by kirill-konshin** [comment]
Yep, I see the issue, let me investigate.

**Comment by kirill-konshin** [comment]
Released `0.4.0`. Thanks for your help!
